### ISSUE TITLE
`TypeError: process.send is not a function` when importing `Generator`

### ISSUE THREAD

**Issue by AlexMeuer** [yellicode/templating#2]
Following error stems from `import {TextWriter, Generator}                                from '@yellicode/templating';`
```
 error in require for [@yellicode/templating]:
> TypeError: process.send is not a function
    at InternalGenerator.sendProcessMessage (/foo/bar/node_modules/@yellicode/templating/dist/bundles/templating.umd.js:352:21)
    at new InternalGenerator (/foo/bar/node_modules/@yellicode/templating/dist/bundles/templating.umd.js:313:18)
    at /foo/bar/node_modules/@yellicode/templating/dist/bundles/templating.umd.js:518:23
    at /foo/bar/node_modules/@yellicode/templating/dist/bundles/templating.umd.js:2:68
    at Object.<anonymous> (/foo/bar/node_modules/@yellicode/templating/dist/bundles/templating.umd.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Object.require.extensions.(anonymous function) [as .js] (/redacted/node_modules/ts-node/src/index.ts:431:14)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)

```
**Versions**
npm: 6.9.0
node: v11.4.0
yellicode:
-core: 1.1.3
-csharp: 1.7.1
-elements: 1.1.0
-templating: 1.5.0

**Comment by mdelaat** [comment]
I cannot reproduce this issue yet (using the same package versions but using node.js 8.12.0). Do you get the same issue when using the setup created with the [yellicode init](https://www.yellicode.com/docs/cli) command?

**Comment by AlexMeuer** [comment]
Sorry, I can't say; Went with a different solution and don't have yellicode anymore.
